name: Simple GitHub Actions Demo
on: [push]
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, world! This is a simple GitHub Actions workflow."
      - name: Build
        run: yarn build